# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  name: dtf-deploy

steps:
- script: |
    echo "Hola desde Azure DevOps"
    hostname
    whoami
    uname -a
  displayName: "Prueba agente self-hosted"
